@startuml diagram

actor U1

U1 -> fxui: cleanE.fxml
fxui -> core: appendTask()
core -> fxui: updateListViews()
fxui -> core: handleSaveButton()
core -> savestates: Json
fxui -> core: loadFromFile()
core -> savestates: Json
savestates -> core: Json
core -> fxui: updateListViews()
fxui-> core: handleCompletedTask()
core -> fxui: updateListViews()
fxui -> core: leaderBoardList()
core -> fxui: scoreList

@enduml