@startuml diagram

actor U1

U1 -> RemoteCleanEController: Legg til oppgave
RemoteCleanEController -> RemoteCleanEAccess: addTask(Task)
RemoteCleanEAccess -> ResponseController: HTTP PUT
ResponseController -> RemoteCleanEAccess: 200
RemoteCleanEController -> RemoteCleanEAccess: getTasks()
RemoteCleanEAccess -> ResponseController: HTTP GET
ResponseController -> RemoteCleanEAccess: Response


@enduml